background_opacity 0.7

foreground #e3e4c2
background #0e0e0e
selection_foreground #000000
selection_background #D7D9A7

color0  #405e4c
color1  #647b5d
color2  #65845b 
color3  #728a66
color4  #9aaa7c 
color5  #aeb986
color6  #bbc494 
color7  #efe9c4